// Package sync is the 同步底座 (§五 of docs/p1-tech-plan.md): change log append,
// client_request_id idempotency and the delta cursor read.
//
// Schema authority is the published migration, not this file:
//   - server/migrations/{code}/{code}_0003_change_log_idempotency.up.sql
//
// The structs below mirror that DDL column-for-column. They are deliberately
// unexported and carry no TableName(): the physical table is "{code}_change_log" /
// "{code}_idempotency", and the {code} only exists on a Repo. Any exported row type
// would offer every caller a default table name that no real database has, so every
// read and write here goes through an explicit .Table(...) resolved from the code.
package sync

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"time"

	"gorm.io/gorm"
)

// changeLog is a row of {code}_change_log.
//
// The column set is exactly the six columns §五 (docs/p1-tech-plan.md:282) names, and
// the migration repeats the rule verbatim at finance_0003/homeos_0003:10 --
// 「列集合就是 §五 那六个字，不增不减」:
//
//	(lsn bigserial, family_id, entity, entity_id, op, version)
//
// There is no payload/data column, and that is a decision, not an omission: §五:283
// defines delta as 「GET /api/{code}/sync/changes?family_id&since_lsn&limit，每服务一条
// 游标」 -- it hands out a change *list*, and the client re-reads each object by
// (entity, entity_id). Storing the post-change body in the log would turn
// {code}_change_log into a second data source, which §六 forbids (「动态流与搜索共用
// {code}_change_log，避免两套变更捕获」 -- both readers only see these six columns).
//
// lsn is a bigserial generated by the database; it is only ever read back.
type changeLog struct {
	LSN      uint64 `gorm:"column:lsn;primaryKey"`
	FamilyID string `gorm:"column:family_id;not null"`
	Entity   string `gorm:"column:entity;not null"`
	EntityID string `gorm:"column:entity_id;not null"`
	Op       string `gorm:"column:op;not null"` // CREATE / UPDATE / DELETE, not enumerated by the doc -> no CHECK
	Version  int64  `gorm:"column:version;not null"`
}

// idempotencyKey is a row of {code}_idempotency.
//
// Column set = §五:280 (docs/p1-tech-plan.md:280) verbatim, which is also what
// finance_0003/homeos_0003 CREATE:
//
//	(key, family_id, request_hash, response_snapshot, created_at)
//
// Uniqueness is the (family_id, key) index the migration creates
// ({code}_idempotency_family_key_uidx), NOT a key-only and NOT a request_hash index --
// §五:280 says 「唯一索引」 without naming the columns, and the published DDL settles it
// family-scoped per docs/p1-tech-plan.md:151 「索引第一列固定 family_id」. The tags below
// describe that shape; the migrations are what actually create it (this package never
// runs AutoMigrate).
type idempotencyKey struct {
	Key              string    `gorm:"column:key;not null;uniqueIndex:idempotency_family_key,priority:2"`
	FamilyID         string    `gorm:"column:family_id;not null;uniqueIndex:idempotency_family_key,priority:1"`
	RequestHash      string    `gorm:"column:request_hash;not null"`
	ResponseSnapshot []byte    `gorm:"column:response_snapshot"` // §五 「重放返回首次响应」 -> the first response body
	CreatedAt        time.Time `gorm:"column:created_at;not null"`
}

// DeltaQuery represents parameters for querying changes.
type DeltaQuery struct {
	FamilyID string
	SinceLSN uint64
	Limit    int
}

// DeltaEntry is one item of GET /api/{code}/sync/changes.
//
// It carries no data body: §五:283 defines the delta response as the change list, and
// §五:282 gives {code}_change_log exactly the columns listed here. The client fetches
// the object itself by (entity, entity_id).
type DeltaEntry struct {
	LSN      uint64 `json:"lsn"`
	Entity   string `json:"entity"`
	EntityID string `json:"entity_id"`
	Op       string `json:"op"`
	Version  int64  `json:"version"`
}

// serviceCodePattern is the shape of a registry service code (homeos, finance, ...).
// The code is interpolated into table names, so anything looser than this is either a
// bug ("", " finance") or an injection attempt ("a;drop table x").
var serviceCodePattern = regexp.MustCompile(`^[a-z][a-z0-9_]{0,62}$`)

// Repo is the base class for sync repository operations.
// Business write operations append to {code}_change_log within transactions.
//
// The zero value is not usable and neither is a Repo built with an empty/invalid code:
// every method returns the error captured at construction instead of falling back to a
// table name that does not exist anywhere.
type Repo struct {
	db        *gorm.DB
	code      string
	tableName string
	idemTable string
	err       error
}

// NewRepo creates a new sync repository instance.
// code is the service code (e.g., "homeos", "finance"). The physical tables it reads
// and writes are "{code}_change_log" and "{code}_idempotency" -- the same names the
// 0003 migration creates inside schema "{code}" (the DSN pins search_path={code}, see
// packages/obs/config.go).
func NewRepo(db *gorm.DB, code string) *Repo {
	if db == nil {
		return &Repo{code: code, err: errors.New("sync: NewRepo requires a non-nil *gorm.DB")}
	}
	if !serviceCodePattern.MatchString(code) {
		return &Repo{code: code, err: fmt.Errorf("sync: NewRepo service code %q is not a valid {code} (^[a-z][a-z0-9_]*$)", code)}
	}
	return &Repo{
		db:        db,
		code:      code,
		tableName: fmt.Sprintf("%s_change_log", code),
		idemTable: fmt.Sprintf("%s_idempotency", code),
	}
}

// Table reports the change-log table this Repo writes (it is "{code}_change_log").
func (r *Repo) Table() string { return r.tableName }

// IdempotencyTable reports the idempotency table this Repo writes (it is "{code}_idempotency").
func (r *Repo) IdempotencyTable() string { return r.idemTable }

// Err returns the construction error, if any (bad code / nil handle).
func (r *Repo) Err() error { return r.err }

// AppendChangeLog appends a change log entry within a transaction.
// This should be called from business write operations.
//
// data is accepted and deliberately NOT persisted: {code}_change_log has no payload
// column (§五:282 -- the log is the six-column change list, the object body stays in
// the business table, which is what the client re-reads via delta). Callers pass the
// row they just wrote; it is ignored rather than smuggled into an undeclared column.
func (r *Repo) AppendChangeLog(ctx context.Context, tx *gorm.DB, familyID, entity, entityID, op string, version int64, data interface{}) error {
	_ = data
	if r.err != nil {
		return r.err
	}
	if tx == nil {
		return fmt.Errorf("sync: AppendChangeLog(%s) requires the enclosing transaction handle", r.tableName)
	}

	row := changeLog{
		FamilyID: familyID,
		Entity:   entity,
		EntityID: entityID,
		Op:       op,
		Version:  version,
	}

	// Use the code-specific table name -- never the row type's own naming.
	if err := tx.Table(r.tableName).WithContext(ctx).Create(&row).Error; err != nil {
		return fmt.Errorf("sync: append to %s: %w", r.tableName, err)
	}
	return nil
}

// CheckIdempotency checks if a request has already been processed.
// Returns true and the cached response if found.
func (r *Repo) CheckIdempotency(ctx context.Context, tx *gorm.DB, key, familyID string, requestData interface{}) (bool, []byte, error) {
	if r.err != nil {
		return false, nil, r.err
	}
	if tx == nil {
		return false, nil, fmt.Errorf("sync: CheckIdempotency(%s) requires the enclosing transaction handle", r.idemTable)
	}
	hash := computeRequestHash(requestData)

	var row idempotencyKey
	result := tx.Table(r.idemTable).WithContext(ctx).
		Where("key = ? AND family_id = ?", key, familyID).
		First(&row)

	if result.Error == gorm.ErrRecordNotFound {
		return false, nil, nil
	}
	if result.Error != nil {
		return false, nil, fmt.Errorf("sync: read %s: %w", r.idemTable, result.Error)
	}

	// Verify hash matches
	if row.RequestHash != hash {
		return false, nil, nil
	}

	return true, row.ResponseSnapshot, nil
}

// RecordIdempotency records a successful request for idempotency checking.
func (r *Repo) RecordIdempotency(ctx context.Context, tx *gorm.DB, key, familyID string, requestData interface{}, response interface{}) error {
	if r.err != nil {
		return r.err
	}
	if tx == nil {
		return fmt.Errorf("sync: RecordIdempotency(%s) requires the enclosing transaction handle", r.idemTable)
	}
	hash := computeRequestHash(requestData)

	responseBytes, err := json.Marshal(response)
	if err != nil {
		return fmt.Errorf("sync: failed to marshal response: %w", err)
	}

	row := idempotencyKey{
		Key:              key,
		FamilyID:         familyID,
		RequestHash:      hash,
		ResponseSnapshot: responseBytes,
		CreatedAt:        time.Now().UTC(),
	}

	if err := tx.Table(r.idemTable).WithContext(ctx).Create(&row).Error; err != nil {
		return fmt.Errorf("sync: insert into %s: %w", r.idemTable, err)
	}
	return nil
}

// GetChanges returns delta changes since the given LSN.
// Implements GET /api/{code}/sync/changes?family_id&since_lsn&limit
func (r *Repo) GetChanges(ctx context.Context, query DeltaQuery) ([]DeltaEntry, error) {
	if r.err != nil {
		return nil, r.err
	}
	if query.Limit <= 0 {
		query.Limit = 100 // Default limit
	}
	if query.Limit > 1000 {
		query.Limit = 1000 // Max limit
	}

	var rows []changeLog
	result := r.db.WithContext(ctx).Table(r.tableName).
		Where("family_id = ? AND lsn > ?", query.FamilyID, query.SinceLSN).
		Order("lsn ASC").
		Limit(query.Limit).
		Find(&rows)

	if result.Error != nil {
		return nil, fmt.Errorf("sync: failed to get changes: %w", result.Error)
	}

	entries := make([]DeltaEntry, 0, len(rows))
	for _, row := range rows {
		entries = append(entries, DeltaEntry{
			LSN:      row.LSN,
			Entity:   row.Entity,
			EntityID: row.EntityID,
			Op:       row.Op,
			Version:  row.Version,
		})
	}

	return entries, nil
}

// computeRequestHash computes a SHA256 hash of the request data.
func computeRequestHash(data interface{}) string {
	bytes, err := json.Marshal(data)
	if err != nil {
		return ""
	}
	hash := sha256.Sum256(bytes)
	return hex.EncodeToString(hash[:])
}
