package model_test

import (
	"testing"
	"time"

	"github.com/xueshuaihui/HomeCube/server/services/svc-finance/internal/model"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// setupTestDB creates an in-memory SQLite database and auto-migrates all finance models.
func setupTestDB(t *testing.T) *gorm.DB {
	t.Helper()

	// Set table prefix to empty for SQLite testing
	model.TablePrefix = ""

	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("failed to open test database: %v", err)
	}

	// Migrate all finance models
	err = db.AutoMigrate(
		&model.FinanceAccount{},
		&model.FinanceCategory{},
		&model.FinanceTransaction{},
		&model.FinanceLedger{},
	)
	if err != nil {
		t.Fatalf("failed to migrate models: %v", err)
	}

	return db
}

func TestFinanceAccountModel(t *testing.T) {
	db := setupTestDB(t)

	// Test creating an account
	account := &model.FinanceAccount{
		FamilyID: "test-family-001",
		Name:     "Test Account",
		Type:     "bank",
		Balance:  100000, // $1000.00 in cents
		Version:  1,
	}

	result := db.Create(account)
	if result.Error != nil {
		t.Fatalf("failed to create account: %v", result.Error)
	}

	// Note: ID is not auto-generated in tests; it's generated by the repo layer in production

	// Test retrieving the account
	var retrieved model.FinanceAccount
	result = db.First(&retrieved, "id = ?", account.ID)
	if result.Error != nil {
		t.Fatalf("failed to retrieve account: %v", result.Error)
	}

	if retrieved.Name != account.Name {
		t.Errorf("expected name %s, got %s", account.Name, retrieved.Name)
	}

	if retrieved.Balance != account.Balance {
		t.Errorf("expected balance %d, got %d", account.Balance, retrieved.Balance)
	}

	// Test TableName method
	expectedTable := "finance_account"
	if account.TableName() != expectedTable {
		t.Errorf("expected table name %s, got %s", expectedTable, account.TableName())
	}
}

func TestFinanceCategoryModel(t *testing.T) {
	db := setupTestDB(t)

	// Test creating a category
	category := &model.FinanceCategory{
		FamilyID:  "test-family-001",
		Name:      "Food",
		Icon:      "🍔",
		SortOrder: 1,
		IsActive:  true,
		Version:   1,
	}

	result := db.Create(category)
	if result.Error != nil {
		t.Fatalf("failed to create category: %v", result.Error)
	}

	// Note: ID is not auto-generated in tests; it's generated by the repo layer in production

	// Test retrieving the category
	var retrieved model.FinanceCategory
	result = db.First(&retrieved, "id = ?", category.ID)
	if result.Error != nil {
		t.Fatalf("failed to retrieve category: %v", result.Error)
	}

	if retrieved.Name != category.Name {
		t.Errorf("expected name %s, got %s", category.Name, retrieved.Name)
	}

	// Test TableName method
	expectedTable := "finance_category"
	if category.TableName() != expectedTable {
		t.Errorf("expected table name %s, got %s", expectedTable, category.TableName())
	}
}

func TestFinanceTransactionModel(t *testing.T) {
	db := setupTestDB(t)

	now := time.Now()

	// Test creating a transaction
	transaction := &model.FinanceTransaction{
		FamilyID:    "test-family-001",
		Type:        "expense",
		AmountCents: -5000, // -$50.00 in cents
		AccountID:   "test-account-001",
		OccurredAt:  now,
		Description: "Lunch",
		Version:     1,
	}

	result := db.Create(transaction)
	if result.Error != nil {
		t.Fatalf("failed to create transaction: %v", result.Error)
	}

	// Note: ID is not auto-generated in tests; it's generated by the repo layer in production

	// Test retrieving the transaction
	var retrieved model.FinanceTransaction
	result = db.First(&retrieved, "id = ?", transaction.ID)
	if result.Error != nil {
		t.Fatalf("failed to retrieve transaction: %v", result.Error)
	}

	if retrieved.Type != transaction.Type {
		t.Errorf("expected type %s, got %s", transaction.Type, retrieved.Type)
	}

	if retrieved.AmountCents != transaction.AmountCents {
		t.Errorf("expected amount %d, got %d", transaction.AmountCents, retrieved.AmountCents)
	}

	// Test TableName method
	expectedTable := "finance_transaction"
	if transaction.TableName() != expectedTable {
		t.Errorf("expected table name %s, got %s", expectedTable, transaction.TableName())
	}
}

func TestFinanceLedgerModel(t *testing.T) {
	db := setupTestDB(t)

	// Test creating a ledger
	ledger := &model.FinanceLedger{
		FamilyID:    "test-family-001",
		Name:        "2024 Budget",
		MemberIDs:   []string{"member-001", "member-002"},
		PeriodStart: time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC),
		PeriodEnd:   time.Date(2024, 12, 31, 0, 0, 0, 0, time.UTC),
		SortOrder:   1,
		Version:     1,
	}

	result := db.Create(ledger)
	if result.Error != nil {
		t.Fatalf("failed to create ledger: %v", result.Error)
	}

	// Note: ID is not auto-generated in tests; it's generated by the repo layer in production

	// Test retrieving the ledger
	var retrieved model.FinanceLedger
	result = db.First(&retrieved, "id = ?", ledger.ID)
	if result.Error != nil {
		t.Fatalf("failed to retrieve ledger: %v", result.Error)
	}

	if retrieved.Name != ledger.Name {
		t.Errorf("expected name %s, got %s", ledger.Name, retrieved.Name)
	}

	if len(retrieved.MemberIDs) != len(ledger.MemberIDs) {
		t.Errorf("expected %d members, got %d", len(ledger.MemberIDs), len(retrieved.MemberIDs))
	}

	// Test TableName method
	expectedTable := "finance_ledger"
	if ledger.TableName() != expectedTable {
		t.Errorf("expected table name %s, got %s", expectedTable, ledger.TableName())
	}
}

func TestSoftDelete(t *testing.T) {
	db := setupTestDB(t)

	// Create an account
	account := &model.FinanceAccount{
		FamilyID: "test-family-001",
		Name:     "To Be Deleted",
		Type:     "cash",
		Balance:  0,
		Version:  1,
	}

	result := db.Create(account)
	if result.Error != nil {
		t.Fatalf("failed to create account: %v", result.Error)
	}

	// Soft delete the account
	result = db.Where("id = ?", account.ID).Delete(account)
	if result.Error != nil {
		t.Fatalf("failed to soft delete account: %v", result.Error)
	}

	// Verify it's not returned in normal queries
	var count int64
	db.Model(&model.FinanceAccount{}).Where("family_id = ?", "test-family-001").Count(&count)
	if count != 0 {
		t.Errorf("expected 0 active accounts after soft delete, got %d", count)
	}

	// Verify it still exists with deleted_at set
	var deletedAccount model.FinanceAccount
	result = db.Unscoped().First(&deletedAccount, "id = ?", account.ID)
	if result.Error != nil {
		t.Fatalf("failed to retrieve soft-deleted account: %v", result.Error)
	}

	if deletedAccount.DeletedAt.Valid == false {
		t.Error("expected deleted_at to be set")
	}
}
